---

- name: installing kubernates nfs
  hosts: nfs
  vars_files:
    - "group_vars/common.yaml"
    - "group_vars/nfs.yaml"
    - "group_vars/common-podman.yaml"
  gather_facts: false
  roles:
    - common
    - nfs
    - common-podman
