---

- name: installing kubernates master
  hosts: master
  vars_files:
    - "group_vars/common.yaml"
    - "group_vars/common-podman.yaml"
  gather_facts: false
  roles:
    - common
    - common-podman
    - master
