---

- name: copy file to workers
  hosts: workers
  gather_facts: false
  tasks:
    - name: Copy Remote-To-Remote
      synchronize: src=/home/ansible/tmp.conf dest=/home/ansible/tmp.conf
      delegate_to: master
      become: yes
    - name: Copy admin.conf
      synchronize: src=/etc/kubernetes/admin.conf dest=/etc/kubernetes/admin.conf
      delegate_to: master
      become: yes