---

- name: deluser -md /home/kubeadmin kubeadmin
  command: "deluser -md /home/{{user}} {{user}}"
  become: yes

- name: rm -rf /home/{{user}}/.kube
  command: "rm -rf /home/{{user}}/.kube"
  become: yes
