---

- name: vgchange -a n data_vg
  command: "vgchange -a n {{volume_group}}"
  become: yes

- name: vgremove data_vg -y
  command: "vgremove {{volume_group}} -y"
  become: yes

- name: rm -rf /srv/nfs
  command: "rm -r /srv/nfs"
  become: yes