---

- name: mkdir -p ~/.kube
  command: "mkdir -p ~/.kube"
  become: yes

- name: cp -i /etc/kubernetes/admin.conf ~/.kube/config
  command: "cp -i /etc/kubernetes/admin.conf ~/.kube/config"
  become: yes

- name: chown $(id -u):$(id -g) ~/.kube/config
  become: yes
  file:
      path: ~/.kube/config
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0644
