---

- name: touch /etc/sysctl.d/k8s.conf
  command: "touch /etc/sysctl.d/k8s.conf"
  become: yes

- name: agregando contenido a /etc/sysctl.d/k8s.conf
  shell: |
      cat <<EOF > /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      EOF
  become: yes

- name: sysctl --system
  command: "sysctl --system"
  become: yes

- name: swapoff -a
  command: "swapoff -a"
  become: yes
