---

- name: cat <<EOF > /etc/sysctl.d/k8s.conf
  command: "cat <<EOF > /etc/sysctl.d/k8s.conf"
  become: yes

- name: sysctl --system
  command: "sysctl --system"
  become: yes

- name: swapoff -a
  command: "swapoff -a"
  become: yes
