---

- name: touch /etc/sysctl.d/k8s
  command: "touch /etc/sysctl.d/k8s.conf"
  become: yes

- name: 'agregando contenido a /etc/sysctl.d/k8s'
  lineinfile:
    path: "/etc/sysctl.d/k8s.conf"
    line: "{{item}}"
    state: present
  become: yes
  with_items:
    - "{{k8s.content}}"

- name: sysctl --system
  command: "sysctl --system"
  become: yes

- name: swapoff -a
  command: "swapoff -a"
  become: yes
