---

- name: touch /etc/sysctl.d/k8s.conf
  command: "touch /etc/sysctl.d/k8s.conf"
  become: yes

- name: agregando contenido a /etc/sysctl.d/k8s.conf
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: "{{item.ip}}"
    state: present
  become: yes
  with_items:
    - "{{hosts}}"

- name: sysctl --system
  command: "sysctl --system"
  become: yes

- name: swapoff -a
  command: "swapoff -a"
  become: yes
