---

- name: touch /etc/sysctl.d/k8s.conf
  command: "touch /etc/sysctl.d/k8s.conf"
  become: yes

- name: bash -c 'echo "net.bridge.bridge-nf-call-ip6tables = 1" > /etc/sysctl.d/k8s.conf'
  command: "bash -c 'echo \"net.bridge.bridge-nf-call-ip6tables = 1\" > /etc/sysctl.d/k8s.conf'"
  become: yes

- name: bash -c 'echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.d/k8s.conf'
  command: "bash -c 'echo \"net.bridge.bridge-nf-call-iptables = 1\" >> /etc/sysctl.d/k8s.conf'"
  become: yes

- name: sysctl --system
  command: "sysctl --system"
  become: yes

- name: cat <<EOF > /etc/sysctl.d/k8s.conf
  command: "cat <<EOF > /etc/sysctl.d/k8s.conf"
  become: yes

- name: sysctl --system
  command: "sysctl --system"
  become: yes

- name: swapoff -a
  command: "swapoff -a"
  become: yes
