---

- name: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  command: "dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"
  become: yes

- name: dnf install docker-ce-19.03.14-3.el8 containerd.io -y --allowerasing
  command: "dnf install docker-ce-19.03.14-3.el8 containerd.io -y --allowerasing"
  become: yes

- name: systemctl enable docker
  command: "systemctl enable docker"
  become: yes

- name: systemctl start docker
  command: "systemctl start docker"
  become: yes