---

- name: touch /etc/yum.repos.d/kubernetes.repo
  command: "touch /etc/yum.repos.d/kubernetes.repo"
  become: yes

- name: agregando contenido a /etc/yum.repos.d/kubernetes.repo
  lineinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    line: "{{item}}"
    state: present
  become: yes
  with_items:
    - "{{kubernate.repo.content}}"

- name: dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
  command: "dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes"
  become: yes

- name: systemctl enable kubelet
  command: "systemctl enable kubelet"
  become: yes

- name: systemctl start kubelet
  command: "systemctl start kubelet"
  become: yes