---

- name: agregando host en /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: "/dev/mapper/cs-{{ansible_play_hosts}}-swap     none                    swap    defaults        0 0"
    state: present
  become: yes

- name: swapon -a
  command: "swapon -a"
  become: yes
