---

- name: Se claimea el persistent volume
  command: "kubectl apply -f {{path}}{{persistent_volume}}"
  become: yes

- name: Se claimea el poder asignarle volumen al POD
  command: "kubectl apply -f {{path}}{{volume_to_pod}}"
  become: yes

- name: Se deploya el app
  command: "kubectl apply -f {{path}}{{app_file}}"
  become: yes