---

- name: kubeadm config images pull
  command: "kubeadm config images pull"
  become: yes

- name: firewall-cmd --permanent --add-rich-rule 'rule family=ipv4 source address=192.168.81.130/24 accept'
  command: "firewall-cmd --permanent --add-rich-rule 'rule family=ipv4 source address={{worker1-ip}} accept'"
  become: yes

- name: firewall-cmd --permanent --add-rich-rule 'rule family=ipv4 source address=192.168.81.131/24 accept'
  command: "firewall-cmd --permanent --add-rich-rule 'rule family=ipv4 source address={{worker2-ip}} accept'"
  become: yes

- name: firewall-cmd --reload
  command: "firewall-cmd --reload"
  become: yes

- name: firewall-cmd --zone=public --permanent --add-rich-rule 'rule family=ipv4 source address=172.17.0.0/16 accept'
  command: "firewall-cmd --zone=public --permanent --add-rich-rule 'rule family=ipv4 source address={{master-ip}} accept'"
  become: yes

- name: firewall-cmd --reload
  command: "firewall-cmd --reload"
  become: yes