---
- name: kubeadm reset
  shell: "sudo kubeadm reset --ignore-preflight-errors=all --force"
  register: reset_cluster

- name: kubeadm init
  when: reset_cluster is succeeded
  shell: |
    sudo kubeadm init --pod-network-cidr 192.169.0.0/16 --ignore-preflight-errors=all
  register: init_cluster

- name: copy init_cluster
  when: init_cluster is succeeded
  local_action: copy content={{init_cluster.stdout | regex_search(regexp,'^kubeadm$') }} dest=~/tmp.conf