---
- name: kubeadm reset
  shell: "kubeadm reset --ignore-preflight-errors=all --force"
  register: reset_cluster
  become: yes

- name: kubeadm init
  when: reset_cluster is succeeded
  shell: |
    kubeadm init --pod-network-cidr {{network_cidr}} --ignore-preflight-errors=all
  register: init_cluster
  become: yes

- name: copy init_cluster
  when: init_cluster is succeeded
  local_action: copy content={{init_cluster.stdout}} dest=~/tmp.conf
  become: yes