---

- name: mkdir -p /home/ansible/.kube
  command: "mkdir -p /home/ansible/.kube"
  become: yes

- name: cp -i /etc/kubernetes/admin.conf /home/ansible/.kube/config
  command: "cp -i /etc/kubernetes/admin.conf /home/ansible/.kube/config"
  become: yes

- name: chown $(id -u):$(id -g) /home/ansible/.kube/config
  become: yes
  file:
      path: /home/ansible/.kube/config
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0644
